### ISSUE TITLE
SPIRV*Adaptor passes are not updated to work with new LLVM pass manager

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/vc-intrinsics#52]
LLVM has switched to use new pass manager by default in llvm/llvm-project@669ddd1e9b1226432b003dbba05b99f8e992285b and lack of support of new pass manager from vc-intrinsics side blocks uplifting intel/llvm project to newer LLVM version: intel/llvm#3183

**Comment by aus-intel** [comment]
PR with preparational changes: https://github.com/intel/vc-intrinsics/pull/55.

**Comment by aus-intel** [comment]
Issue with writer adaptor should be fixed with #57. This unblocks intel/llvm project since this is the only pass that it uses.

**Comment by AlexeySachkov** [comment]
Thanks!
